#!/usr/bin/env python3
"""Merge per-line solution.md files into solution.jsonl.

Expected run directory structure from run_test_jsonl.py:
  <runs_dir>/
    0001_xxx/
    0002_xxx/
    ...

This script reads test.jsonl line-by-line, finds the corresponding run
directory by line prefix (e.g. 0002_), reads solution.md, and writes
solution.jsonl with an added "solution" field per row.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


LINE_PREFIX_PATTERN = re.compile(r"^(\d+)_")


def parse_args() -> argparse.Namespace:
    script_path = Path(__file__).resolve()
    project_root = script_path.parents[3]

    parser = argparse.ArgumentParser(
        description="Merge solution.md files into test.jsonl rows as 'solution'."
    )
    parser.add_argument(
        "--jsonl",
        type=Path,
        default=project_root / "test.jsonl",
        help="Input source jsonl (default: ./test.jsonl).",
    )
    parser.add_argument(
        "--runs-dir",
        type=Path,
        required=True,
        help="Base run dir generated by run_test_jsonl.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default="solution.jsonl",
        help="Output jsonl path (default: <jsonl_dir>/solution.jsonl).",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail if any line cannot find solution.md.",
    )
    return parser.parse_args()


def find_solution_file(row_run_dir: Path) -> Path | None:
    candidates = [
        row_run_dir / "workspaces" / "task_0" / "solution.md",
        row_run_dir / "workspace" / "solution.md",
        row_run_dir / "solution.md",
    ]
    for path in candidates:
        if path.exists():
            return path

    extra = sorted(row_run_dir.rglob("solution.md"))
    if extra:
        return extra[0]
    return None


def build_latest_run_map(runs_dir: Path) -> dict[int, Path]:
    line_to_run_dirs: dict[int, list[Path]] = {}

    for child in runs_dir.iterdir():
        if not child.is_dir():
            continue
        match = LINE_PREFIX_PATTERN.match(child.name)
        if not match:
            continue
        line_no = int(match.group(1))
        line_to_run_dirs.setdefault(line_no, []).append(child)

    latest_map: dict[int, Path] = {}
    for line_no, dirs in line_to_run_dirs.items():
        latest_map[line_no] = max(dirs, key=lambda p: p.stat().st_mtime)
    return latest_map


def main() -> int:
    args = parse_args()
    output_path = args.output or (args.jsonl.parent / "solution.jsonl")

    if not args.jsonl.exists():
        print(f"[ERROR] jsonl not found: {args.jsonl}")
        return 1
    if not args.runs_dir.exists():
        print(f"[ERROR] runs dir not found: {args.runs_dir}")
        return 1

    run_map = build_latest_run_map(args.runs_dir)
    total = 0
    with_solution = 0
    missing_lines: list[int] = []

    with args.jsonl.open("r", encoding="utf-8") as f_in, output_path.open(
        "w", encoding="utf-8"
    ) as f_out:
        for line_no, raw in enumerate(f_in, start=1):
            stripped = raw.strip()
            if not stripped:
                continue

            try:
                row = json.loads(stripped)
            except json.JSONDecodeError as exc:
                print(f"[ERROR] invalid json at line {line_no}: {exc}")
                return 1
            if not isinstance(row, dict):
                print(f"[ERROR] line {line_no} is not a JSON object")
                return 1

            solution_text = ""
            row_run_dir = run_map.get(line_no)
            if row_run_dir is not None:
                solution_file = find_solution_file(row_run_dir)
                if solution_file is not None:
                    solution_text = solution_file.read_text(encoding="utf-8")

            if solution_text:
                with_solution += 1
            else:
                missing_lines.append(line_no)

            row["solution"] = solution_text
            f_out.write(json.dumps(row, ensure_ascii=False) + "\n")
            total += 1

    print("=" * 60)
    print(f"[DONE] output: {output_path}")
    print(f"[DONE] rows={total}, rows_with_solution={with_solution}, rows_missing={len(missing_lines)}")
    if missing_lines:
        preview = ", ".join(str(n) for n in missing_lines[:20])
        print(f"[WARN] missing solution lines (first 20): {preview}")
        if args.strict:
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
